image: golang:1.23

stages:
  - code-quality

code-quality:
  stage: code-quality
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - go mod download
    - go vet ./...
    - test -z "$(gofmt -l .)"
    - go test ./...
