image: php:8.3-cli

stages:
  - code-quality

code-quality:
  stage: code-quality
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - composer install --no-interaction
    - vendor/bin/phpcs
    - vendor/bin/phpstan analyse
