image: composer:2

stages:
  - code-quality

code-quality:
  stage: code-quality
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - composer install --no-interaction --prefer-dist
    - composer lint
    - composer analyse
    - composer test
