image: php:8.3-cli

pipelines:
  pull-requests:
    '**':
      - step:
          name: Code Quality
          script:
            - composer install --no-interaction
            - vendor/bin/phpcs
            - vendor/bin/phpstan analyse
