pipeline {
    agent { docker { image 'php:8.3-cli' } }

    stages {
        stage('Code Quality') {
            steps {
                sh 'composer install --no-interaction'
                sh 'vendor/bin/phpcs'
                sh 'vendor/bin/phpstan analyse'
            }
        }
    }
}
