name: Code Quality

on:
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    container: composer:2
    steps:
      - uses: actions/checkout@v4
      - run: composer install --no-interaction --prefer-dist
      - run: composer lint
      - run: composer analyse
      - run: composer test
