# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= {{ cookiecutter.ruby_version }}"

gem "rackup", "~> 2.1"
gem "sinatra", "~> 4.1"
gem "sinatra-contrib", "~> 4.1"
gem "webrick", "~> 1.9"

group :development, :test do
  gem "puma", "~> 6.4"
  gem "rack-test", "~> 2.1"
  gem "rspec", "~> 3.13"
  gem "rubocop", "~> 1.69", require: false
  gem "rubocop-rspec", "~> 3.3", require: false
end
