library identifier: 'ci-jenkins@v1',
        retriever: modernSCM([$class: 'GitSCMSource',
                              remote: 'https://github.com/actionplatform/ci-jenkins.git'])

apPipeline(image: 'ruby:3.3')
