name: Code Quality

on:
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  code-quality:
    container: python:3.12
    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - run: poetry install
      - run: poetry run mkdocs build --strict
