name: Code Quality

on:
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  code-quality:
    container: maven:3-eclipse-temurin-17
    steps:
      - uses: actions/checkout@v4
      - run: mvn -B verify
