image: rust:1.80

pipelines:
  pull-requests:
    '**':
      - step:
          name: Code Quality
          script:
            - cargo fmt --check
            - cargo clippy -- -D warnings
            - cargo test
