name: Publish to Packagist

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0
      - uses: actionplatform/ci-github/release@v1
        with:
          files: "src/Version.php"
      - uses: actionplatform/ci-github/setup@v1
      - run: composer lint
      - run: composer analyse
      - run: composer test
      - name: Ask Packagist to update
        run: |
          curl -fsS -XPOST -H 'content-type:application/json' \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}" \
            -d "{\"repository\":{\"url\":\"https://github.com/${{ github.repository }}\"}}"
