include:
  - remote: https://raw.githubusercontent.com/actionplatform/ci-gitlab/v1/ci.yml

image: golang:1.23

stages: [test, deploy]

check:
  extends: .ap-check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

commits:
  extends: .ap-conventional-commit

gitflow:
  extends: .ap-gitflow
