image: node:20

stages:
  - code-quality

code-quality:
  stage: code-quality
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - npm ci
    - npm run lint
    - npm run format:check
    - npm test
    - REACT_APP_API_URL=https://example.com/api/v1 npm run build
