name: Code Quality

on:
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - uses: actions/checkout@v4
      - run: go mod download
      - run: go vet ./...
      - run: test -z "$(gofmt -l .)"
      - run: go test ./...
