image: composer:2

pipelines:
  pull-requests:
    '**':
      - step:
          name: Code Quality
          script:
            - composer install --no-interaction --prefer-dist
            - composer lint
            - composer analyse
            - composer test
