image: python:3.12

stages:
  - code-quality

code-quality:
  stage: code-quality
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - pip install poetry
    - poetry install --with dev,code-quality
    - poetry run ruff check .
    - poetry run ruff format --check .
