image: golang:1.23

pipelines:
  pull-requests:
    '**':
      - step:
          name: Code Quality
          script:
            - go mod download
            - go vet ./...
            - test -z "$(gofmt -l .)"
            - go test ./...
