pipeline {
    agent { docker { image 'node:22' } }

    stages {
        stage('Code Quality') {
            steps {
                sh 'npm ci'
                sh 'npm run lint'
                sh 'npm run format'
                sh 'node scripts/check_manifest.js'
                sh 'npm test'
            }
        }
    }
}
