name: Code Quality

on:
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run lint
      - run: npm run format
      - run: npm test
      - run: npm run build
