image: python:3.12

pipelines:
  pull-requests:
    '**':
      - step:
          name: Code Quality
          script:
            - pip install poetry
            - poetry install
            - poetry run mkdocs build --strict
