pipeline {
    agent { docker { image 'python:3.12' } }

    stages {
        stage('Code Quality') {
            steps {
                sh 'pip install poetry'
                sh 'poetry install'
                sh 'poetry run mkdocs build --strict'
            }
        }
    }
}
